CREATE TABLE account_infos (
Id INT AUTO_INCREMENT NOT NULL,
User_id INT NOT NULL,
Account_Name VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
Username VARCHAR(150) NOT NULL,
Password VARCHAR(255) NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (User_Id) REFERENCES Users(user_id));